on: [push]
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
    with:
      php-version: '8.2'
  - run: composer install
  - run: vendor/bin/phpstan analyse
  - run: vendor/bin/pint --test
  - run: vendor/bin/phpunit --coverage-clover=coverage.xml
  - uses: actions/upload-artifact@v4
    with:
      name: coverage
      path: coverage.xml
  - name: Deploy if success
    if: success()
    run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
